---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation
# Linux OS for Servers (3.65)
# Handlers
# ------------------------------------------------------------------------

- name: update grub
  command: '{{ grub_update_tool }}'

- name: restart rsyslog
  service:
    name: 'rsyslog'
    state: restarted

- name: restart auditd
  service:
    name: '{{ audit_deamon }}'
    state: restarted
  when: ansible_os_family != "RedHat"

- name: restart ntp
  service:
    name: '{{ ntp_deamon }}'
    state: restarted
