---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation - Hardening
# SSH (3.04)
# Tasks: 01 SSH Requirements
# ------------------------------------------------------------------------

# Req 1:	The SSH protocol version 2 must be used.
# Req 2:	SSH moduli smaller than 2048 must not be used.

- name: req-002.1 check if /etc/ssh/moduli for short values
  shell: awk '$5 < {{ moduli_minimum }}' /etc/ssh/moduli
  register: ssh_moduli
  changed_when: false
  when: config_ssh_server

- name: req-002.1 remove all primes smaller than defined value
  shell: awk '$5 >= {{ moduli_minimum }}' /etc/ssh/moduli > /etc/ssh/moduli.new ;
         [ -r /etc/ssh/moduli.new -a -s /etc/ssh/moduli.new ] && mv /etc/ssh/moduli.new /etc/ssh/moduli || true
  notify: restart sshd
  when: config_ssh_server and ssh_moduli.stdout != ""

# Req 3:	Only approved key exchange algorithms must be used.
# Req 4:	Only approved ciphers algorithms must be used.
# Req 5:	Only approved MAC algorithms must be used.
# Req 6:	SSH logging must be enabled.
# Req 7:	SSH LoginGraceTime must be set to one minute or less.
# Req 8:	SSH MaxAuthTries must be set to 5 or less.
# Req 9:	SSH root login must be disabled.
# Req 10:	SSH strict mode must be enabled.
# Req 11:	SSH user authentication must be done with public keys.
# Req 12:	SSH password authentication must be disabled.
# Req 13:	SSH IgnoreRhosts must be enabled.
# Req 14:	SSH HostbasedAuthentication must be disabled.
# Req 15:	The usage of the SSH service must be restricted to dedicated groups
# or users.
# Req 16:	The SSH Idle Timeout Interval must be configured to an adequate time.
# Req 17:	SSH tunnel devices must be disabled.
# Req 18:	SSH TCP port forwarding must be disabled.
# Req 19:	SSH agent forwarding must be disabled.
# Req 20:	SSH gateway ports must be disabled.
# Req 21:	SSH X11 forwarding must be disabled.
# Req 22:	SSH PermitUserEnvironment must be disabled.
# Req 23:	SSH PermitEmptyPasswords must be disabled.
# Req 24:	If SFTP is activated, internal server of OpenSSH must be used.

- name: req-024.1 set configuration for sshd (req 1, 3 - 24)
  template:
    src: 'sshdconfig.j2'
    dest: '{{ sshd_conf_file }}'
    owner: "{{ sshd_conf_owner }}"
    group: "{{ sshd_conf_group }}"
    mode: "{{ sshd_conf_mode }}"
  notify: restart sshd
  when: config_ssh_server

- name: req-024.2 generate sftp group
  group:
    name: "{{ sftp_group }}"
    state: present
  when: config_ssh_server and set_sftp_chroot
